services:
  mongodb:
    image: mongo:8.2
    volumes:
      - data:/data/db
  redis:
    image: redis:6
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart:
      always
  server1:
    build: ./backend
    environment:
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - redis
  server2:
    build: ./backend
    environment:
      - PORT=5001
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - redis
  server3:
    build: ./backend
    environment:
      - PORT=5002
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - redis
  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
      - server3
volumes:
  data:
  redis_data: